# Generated by Django 3.1.5 on 2021-05-19 16:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cleverApp', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=200)),
                ('property_status', models.CharField(choices=[('for sale', 'FOR SALE'), ('for rent', 'FOR RENT'), ('other', 'OTHER')], max_length=100)),
                ('property_discription', models.TextField()),
                ('Main_building', models.ImageField(blank=True, upload_to='featured_images')),
                ('sub_building1', models.ImageField(blank=True, upload_to='featured_images')),
                ('sub_building2', models.ImageField(blank=True, upload_to='featured_images')),
                ('sub_building3', models.ImageField(blank=True, upload_to='featured_images')),
                ('sub_building4', models.ImageField(blank=True, upload_to='featured_images')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2021, 5, 19, 16, 32, 29, 702880, tzinfo=utc))),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('property_category', models.CharField(default='uncategorised', max_length=200)),
                ('Poster_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
