# Generated by Django 3.1.5 on 2021-05-28 17:26

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cleverApp', '0005_auto_20210524_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 17, 26, 59, 457908, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='property_discription',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
